name: crossbar-pypy
base: core18
version: 'latest'
version-script: wget -qO- https://pypi.python.org/pypi/crossbar/json | jq .info.version | sed -e 's/^"//' -e 's/"$//'
summary: Crossbar.io - Polyglot application router.
description: |
  Crossbar.io is a networking platform for distributed and microservice
  applications. It is feature rich, scalable, robust and secure. Let
  Crossbar.io take care of the hard parts of messaging so you can focus
  on your app's features.
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

apps:
  crossbar-pypy:
    command: launch.wrapper
    plugs:
      - home
      - network
      - network-bind

parts:
  launcher:
    plugin: dump
    source: .
    stage:
      - launch.wrapper
    prime:
      - launch.wrapper
  crossbar:
    plugin: dump
    source:
      - on amd64: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.2.0-linux64.tar.bz2
      - on i386: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.2.0-linux32.tar.bz2
      - on armhf: https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux-armhf-raspbian.tar.bz2
    override-build: |
      snapcraftctl build
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "armhf" ]; then
        TEMP_LIB_DIR=$(mktemp -d)
        ln -s /usr/lib/arm-linux-gnueabihf/libffi.so $TEMP_LIB_DIR/libffi.so.5
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TEMP_LIB_DIR
      fi
      $SNAPCRAFT_PART_INSTALL/bin/pypy3 -m ensurepip
      $SNAPCRAFT_PART_INSTALL/bin/pypy3 -m pip install crossbar
      $SNAPCRAFT_PART_INSTALL/bin/pypy3 -m compileall -q "$SNAPCRAFT_PRIME"
    stage-packages:
      - libsnappy1v5
      - libssl1.1
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - wget
      - jq
      - dpkg
      - coreutils
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev
