name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Remove LXD
      run: sudo apt purge lxd* -y

    - name: Install LXD snap
      run: sudo snap install lxd

    - name: Setup LXD
      run: sudo /snap/bin/lxd init --auto

    - name: Install Snapcraft
      run: sudo snap install snapcraft --classic

    - uses: actions/checkout@v2
      with:
        repository: 'crossbario/crossbar'

    - name: Build snap
      run: snapcraft --use-lxd
