name: CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'crossbario/crossbar'

    - name: Run a one-line script
      run: ls -la
